# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_dlg.ui'
#
# Created: Mon Feb 27 15:53:35 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1050, 790)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(20, 20, 1011, 741))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.tableWidget = QtGui.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(30, 101, 931, 261))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(12)
        self.tableWidget.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 11, item)
        self.tableWidget_2 = QtGui.QTableWidget(self.tab)
        self.tableWidget_2.setGeometry(QtCore.QRect(90, 450, 821, 251))
        self.tableWidget_2.setObjectName(_fromUtf8("tableWidget_2"))
        self.tableWidget_2.setColumnCount(8)
        self.tableWidget_2.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        self.pushButton = QtGui.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(390, 400, 91, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 380, 75, 23))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(self.tab)
        self.pushButton_3.setGeometry(QtCore.QRect(120, 380, 75, 23))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(30, 20, 161, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(30, 50, 421, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tableWidget_3 = QtGui.QTableWidget(self.tab_2)
        self.tableWidget_3.setGeometry(QtCore.QRect(45, 120, 421, 321))
        self.tableWidget_3.setObjectName(_fromUtf8("tableWidget_3"))
        self.tableWidget_3.setColumnCount(4)
        self.tableWidget_3.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 2, item)
        self.pushButton_4 = QtGui.QPushButton(self.tab_2)
        self.pushButton_4.setGeometry(QtCore.QRect(50, 470, 75, 23))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.pushButton_5 = QtGui.QPushButton(self.tab_2)
        self.pushButton_5.setGeometry(QtCore.QRect(150, 470, 75, 23))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.pushButton_6 = QtGui.QPushButton(self.tab_2)
        self.pushButton_6.setGeometry(QtCore.QRect(390, 470, 75, 23))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(30, 25, 271, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(30, 60, 501, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(370, 80, 151, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_8 = QtGui.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(480, 120, 501, 321))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.formLayoutWidget = QtGui.QWidget(self.tab_3)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 60, 191, 341))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setMargin(0)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.Label1 = QtGui.QLabel(self.formLayoutWidget)
        self.Label1.setObjectName(_fromUtf8("Label1"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.Label1)
        self.DoubleSpinBox1 = QtGui.QDoubleSpinBox(self.formLayoutWidget)
        self.DoubleSpinBox1.setMinimum(-9999.0)
        self.DoubleSpinBox1.setMaximum(9999.0)
        self.DoubleSpinBox1.setProperty("value", 22.0)
        self.DoubleSpinBox1.setObjectName(_fromUtf8("DoubleSpinBox1"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox1)
        self.Label2 = QtGui.QLabel(self.formLayoutWidget)
        self.Label2.setObjectName(_fromUtf8("Label2"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.Label2)
        self.DoubleSpinBox2 = QtGui.QDoubleSpinBox(self.formLayoutWidget)
        self.DoubleSpinBox2.setMinimum(-9999.0)
        self.DoubleSpinBox2.setMaximum(9999.0)
        self.DoubleSpinBox2.setProperty("value", 4.0)
        self.DoubleSpinBox2.setObjectName(_fromUtf8("DoubleSpinBox2"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox2)
        self.Label3 = QtGui.QLabel(self.formLayoutWidget)
        self.Label3.setObjectName(_fromUtf8("Label3"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.Label3)
        self.DoubleSpinBox3 = QtGui.QDoubleSpinBox(self.formLayoutWidget)
        self.DoubleSpinBox3.setMinimum(-9999.0)
        self.DoubleSpinBox3.setMaximum(9999.0)
        self.DoubleSpinBox3.setProperty("value", 4.0)
        self.DoubleSpinBox3.setObjectName(_fromUtf8("DoubleSpinBox3"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox3)
        self.Label4 = QtGui.QLabel(self.formLayoutWidget)
        self.Label4.setObjectName(_fromUtf8("Label4"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.Label4)
        self.DoubleSpinBox4 = QtGui.QDoubleSpinBox(self.formLayoutWidget)
        self.DoubleSpinBox4.setMinimum(-9999.0)
        self.DoubleSpinBox4.setMaximum(9999.0)
        self.DoubleSpinBox4.setProperty("value", 2.23)
        self.DoubleSpinBox4.setObjectName(_fromUtf8("DoubleSpinBox4"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox4)
        self.Label5 = QtGui.QLabel(self.formLayoutWidget)
        self.Label5.setObjectName(_fromUtf8("Label5"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.Label5)
        self.DoubleSpinBox5 = QtGui.QDoubleSpinBox(self.formLayoutWidget)
        self.DoubleSpinBox5.setMinimum(-9999.0)
        self.DoubleSpinBox5.setMaximum(9999.0)
        self.DoubleSpinBox5.setProperty("value", -0.8)
        self.DoubleSpinBox5.setObjectName(_fromUtf8("DoubleSpinBox5"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox5)
        self.Label6 = QtGui.QLabel(self.formLayoutWidget)
        self.Label6.setObjectName(_fromUtf8("Label6"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.Label6)
        self.DoubleSpinBox6 = QtGui.QDoubleSpinBox(self.formLayoutWidget)
        self.DoubleSpinBox6.setMinimum(-9999.0)
        self.DoubleSpinBox6.setMaximum(9999.0)
        self.DoubleSpinBox6.setProperty("value", -0.74)
        self.DoubleSpinBox6.setObjectName(_fromUtf8("DoubleSpinBox6"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox6)
        self.Label7 = QtGui.QLabel(self.formLayoutWidget)
        self.Label7.setObjectName(_fromUtf8("Label7"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.LabelRole, self.Label7)
        self.DoubleSpinBox7 = QtGui.QDoubleSpinBox(self.formLayoutWidget)
        self.DoubleSpinBox7.setMinimum(-9999.0)
        self.DoubleSpinBox7.setMaximum(9999.0)
        self.DoubleSpinBox7.setProperty("value", -0.8)
        self.DoubleSpinBox7.setObjectName(_fromUtf8("DoubleSpinBox7"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox7)
        self.Label8 = QtGui.QLabel(self.formLayoutWidget)
        self.Label8.setObjectName(_fromUtf8("Label8"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.LabelRole, self.Label8)
        self.DoubleSpinBox8 = QtGui.QDoubleSpinBox(self.formLayoutWidget)
        self.DoubleSpinBox8.setMinimum(-9999.0)
        self.DoubleSpinBox8.setMaximum(9999.0)
        self.DoubleSpinBox8.setProperty("value", 4.0)
        self.DoubleSpinBox8.setObjectName(_fromUtf8("DoubleSpinBox8"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox8)
        self.Label9 = QtGui.QLabel(self.formLayoutWidget)
        self.Label9.setObjectName(_fromUtf8("Label9"))
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.LabelRole, self.Label9)
        self.DoubleSpinBox9 = QtGui.QDoubleSpinBox(self.formLayoutWidget)
        self.DoubleSpinBox9.setMinimum(-9999.0)
        self.DoubleSpinBox9.setMaximum(9999.0)
        self.DoubleSpinBox9.setProperty("value", 50.0)
        self.DoubleSpinBox9.setObjectName(_fromUtf8("DoubleSpinBox9"))
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox9)
        self.Label10 = QtGui.QLabel(self.formLayoutWidget)
        self.Label10.setObjectName(_fromUtf8("Label10"))
        self.formLayout_2.setWidget(9, QtGui.QFormLayout.LabelRole, self.Label10)
        self.DoubleSpinBox10 = QtGui.QDoubleSpinBox(self.formLayoutWidget)
        self.DoubleSpinBox10.setMinimum(-9999.0)
        self.DoubleSpinBox10.setMaximum(9999.0)
        self.DoubleSpinBox10.setProperty("value", 9.81)
        self.DoubleSpinBox10.setObjectName(_fromUtf8("DoubleSpinBox10"))
        self.formLayout_2.setWidget(9, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox10)
        self.Label11 = QtGui.QLabel(self.formLayoutWidget)
        self.Label11.setObjectName(_fromUtf8("Label11"))
        self.formLayout_2.setWidget(10, QtGui.QFormLayout.LabelRole, self.Label11)
        self.DoubleSpinBox11 = QtGui.QDoubleSpinBox(self.formLayoutWidget)
        self.DoubleSpinBox11.setMinimum(-9999.0)
        self.DoubleSpinBox11.setMaximum(9999.0)
        self.DoubleSpinBox11.setProperty("value", 0.95)
        self.DoubleSpinBox11.setObjectName(_fromUtf8("DoubleSpinBox11"))
        self.formLayout_2.setWidget(10, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox11)
        self.Label12 = QtGui.QLabel(self.formLayoutWidget)
        self.Label12.setObjectName(_fromUtf8("Label12"))
        self.formLayout_2.setWidget(11, QtGui.QFormLayout.LabelRole, self.Label12)
        self.DoubleSpinBox12 = QtGui.QDoubleSpinBox(self.formLayoutWidget)
        self.DoubleSpinBox12.setMinimum(-9999.0)
        self.DoubleSpinBox12.setMaximum(9999.0)
        self.DoubleSpinBox12.setProperty("value", 1.0)
        self.DoubleSpinBox12.setObjectName(_fromUtf8("DoubleSpinBox12"))
        self.formLayout_2.setWidget(11, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox12)
        self.Label13 = QtGui.QLabel(self.formLayoutWidget)
        self.Label13.setObjectName(_fromUtf8("Label13"))
        self.formLayout_2.setWidget(12, QtGui.QFormLayout.LabelRole, self.Label13)
        self.DoubleSpinBox13 = QtGui.QDoubleSpinBox(self.formLayoutWidget)
        self.DoubleSpinBox13.setMinimum(-9999.0)
        self.DoubleSpinBox13.setMaximum(9999.0)
        self.DoubleSpinBox13.setProperty("value", 1.05)
        self.DoubleSpinBox13.setObjectName(_fromUtf8("DoubleSpinBox13"))
        self.formLayout_2.setWidget(12, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox13)
        self.label_6 = QtGui.QLabel(self.tab_3)
        self.label_6.setGeometry(QtCore.QRect(50, 490, 361, 221))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(520, 500, 411, 191))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayoutWidget_2 = QtGui.QWidget(self.tab_3)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(300, 60, 315, 341))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_3 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setMargin(0)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.Label1_2 = QtGui.QLabel(self.formLayoutWidget_2)
        self.Label1_2.setObjectName(_fromUtf8("Label1_2"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.Label1_2)
        self.DoubleSpinBox1_2 = QtGui.QDoubleSpinBox(self.formLayoutWidget_2)
        self.DoubleSpinBox1_2.setDecimals(3)
        self.DoubleSpinBox1_2.setMinimum(-9999.0)
        self.DoubleSpinBox1_2.setMaximum(9999.0)
        self.DoubleSpinBox1_2.setObjectName(_fromUtf8("DoubleSpinBox1_2"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox1_2)
        self.Label2_2 = QtGui.QLabel(self.formLayoutWidget_2)
        self.Label2_2.setObjectName(_fromUtf8("Label2_2"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.Label2_2)
        self.DoubleSpinBox2_2 = QtGui.QDoubleSpinBox(self.formLayoutWidget_2)
        self.DoubleSpinBox2_2.setDecimals(3)
        self.DoubleSpinBox2_2.setMinimum(-9999.0)
        self.DoubleSpinBox2_2.setMaximum(9999.0)
        self.DoubleSpinBox2_2.setObjectName(_fromUtf8("DoubleSpinBox2_2"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox2_2)
        self.Label3_2 = QtGui.QLabel(self.formLayoutWidget_2)
        self.Label3_2.setObjectName(_fromUtf8("Label3_2"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.Label3_2)
        self.DoubleSpinBox3_2 = QtGui.QDoubleSpinBox(self.formLayoutWidget_2)
        self.DoubleSpinBox3_2.setDecimals(3)
        self.DoubleSpinBox3_2.setMinimum(-9999.0)
        self.DoubleSpinBox3_2.setMaximum(9999.0)
        self.DoubleSpinBox3_2.setObjectName(_fromUtf8("DoubleSpinBox3_2"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox3_2)
        self.DoubleSpinBox4_2 = QtGui.QDoubleSpinBox(self.formLayoutWidget_2)
        self.DoubleSpinBox4_2.setDecimals(3)
        self.DoubleSpinBox4_2.setMinimum(-9999.0)
        self.DoubleSpinBox4_2.setMaximum(9999.0)
        self.DoubleSpinBox4_2.setObjectName(_fromUtf8("DoubleSpinBox4_2"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox4_2)
        self.Label5_2 = QtGui.QLabel(self.formLayoutWidget_2)
        self.Label5_2.setObjectName(_fromUtf8("Label5_2"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.Label5_2)
        self.DoubleSpinBox6_2 = QtGui.QDoubleSpinBox(self.formLayoutWidget_2)
        self.DoubleSpinBox6_2.setDecimals(3)
        self.DoubleSpinBox6_2.setMinimum(-9999.0)
        self.DoubleSpinBox6_2.setMaximum(9999.0)
        self.DoubleSpinBox6_2.setObjectName(_fromUtf8("DoubleSpinBox6_2"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox6_2)
        self.Label7_2 = QtGui.QLabel(self.formLayoutWidget_2)
        self.Label7_2.setObjectName(_fromUtf8("Label7_2"))
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.LabelRole, self.Label7_2)
        self.DoubleSpinBox7_2 = QtGui.QDoubleSpinBox(self.formLayoutWidget_2)
        self.DoubleSpinBox7_2.setDecimals(3)
        self.DoubleSpinBox7_2.setMinimum(-9999.0)
        self.DoubleSpinBox7_2.setMaximum(9999.0)
        self.DoubleSpinBox7_2.setObjectName(_fromUtf8("DoubleSpinBox7_2"))
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox7_2)
        self.Label8_2 = QtGui.QLabel(self.formLayoutWidget_2)
        self.Label8_2.setObjectName(_fromUtf8("Label8_2"))
        self.formLayout_3.setWidget(7, QtGui.QFormLayout.LabelRole, self.Label8_2)
        self.DoubleSpinBox8_2 = QtGui.QDoubleSpinBox(self.formLayoutWidget_2)
        self.DoubleSpinBox8_2.setDecimals(3)
        self.DoubleSpinBox8_2.setMinimum(-9999.0)
        self.DoubleSpinBox8_2.setMaximum(9999.0)
        self.DoubleSpinBox8_2.setObjectName(_fromUtf8("DoubleSpinBox8_2"))
        self.formLayout_3.setWidget(7, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox8_2)
        self.Label9_2 = QtGui.QLabel(self.formLayoutWidget_2)
        self.Label9_2.setObjectName(_fromUtf8("Label9_2"))
        self.formLayout_3.setWidget(8, QtGui.QFormLayout.LabelRole, self.Label9_2)
        self.DoubleSpinBox9_2 = QtGui.QDoubleSpinBox(self.formLayoutWidget_2)
        self.DoubleSpinBox9_2.setDecimals(3)
        self.DoubleSpinBox9_2.setMinimum(-9999.0)
        self.DoubleSpinBox9_2.setMaximum(9999.0)
        self.DoubleSpinBox9_2.setObjectName(_fromUtf8("DoubleSpinBox9_2"))
        self.formLayout_3.setWidget(8, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox9_2)
        self.Label10_2 = QtGui.QLabel(self.formLayoutWidget_2)
        self.Label10_2.setObjectName(_fromUtf8("Label10_2"))
        self.formLayout_3.setWidget(9, QtGui.QFormLayout.LabelRole, self.Label10_2)
        self.DoubleSpinBox10_2 = QtGui.QDoubleSpinBox(self.formLayoutWidget_2)
        self.DoubleSpinBox10_2.setDecimals(3)
        self.DoubleSpinBox10_2.setMinimum(-9999.0)
        self.DoubleSpinBox10_2.setMaximum(9999.0)
        self.DoubleSpinBox10_2.setObjectName(_fromUtf8("DoubleSpinBox10_2"))
        self.formLayout_3.setWidget(9, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox10_2)
        self.Label11_2 = QtGui.QLabel(self.formLayoutWidget_2)
        self.Label11_2.setObjectName(_fromUtf8("Label11_2"))
        self.formLayout_3.setWidget(10, QtGui.QFormLayout.LabelRole, self.Label11_2)
        self.DoubleSpinBox11_2 = QtGui.QDoubleSpinBox(self.formLayoutWidget_2)
        self.DoubleSpinBox11_2.setDecimals(3)
        self.DoubleSpinBox11_2.setMinimum(-9999.0)
        self.DoubleSpinBox11_2.setMaximum(9999.0)
        self.DoubleSpinBox11_2.setObjectName(_fromUtf8("DoubleSpinBox11_2"))
        self.formLayout_3.setWidget(10, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox11_2)
        self.Label12_2 = QtGui.QLabel(self.formLayoutWidget_2)
        self.Label12_2.setObjectName(_fromUtf8("Label12_2"))
        self.formLayout_3.setWidget(11, QtGui.QFormLayout.LabelRole, self.Label12_2)
        self.DoubleSpinBox12_2 = QtGui.QDoubleSpinBox(self.formLayoutWidget_2)
        self.DoubleSpinBox12_2.setDecimals(3)
        self.DoubleSpinBox12_2.setMinimum(-9999.0)
        self.DoubleSpinBox12_2.setMaximum(9999.0)
        self.DoubleSpinBox12_2.setObjectName(_fromUtf8("DoubleSpinBox12_2"))
        self.formLayout_3.setWidget(11, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox12_2)
        self.Label13_2 = QtGui.QLabel(self.formLayoutWidget_2)
        self.Label13_2.setObjectName(_fromUtf8("Label13_2"))
        self.formLayout_3.setWidget(12, QtGui.QFormLayout.LabelRole, self.Label13_2)
        self.DoubleSpinBox13_2 = QtGui.QDoubleSpinBox(self.formLayoutWidget_2)
        self.DoubleSpinBox13_2.setDecimals(3)
        self.DoubleSpinBox13_2.setMinimum(-9999.0)
        self.DoubleSpinBox13_2.setMaximum(9999.0)
        self.DoubleSpinBox13_2.setObjectName(_fromUtf8("DoubleSpinBox13_2"))
        self.formLayout_3.setWidget(12, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox13_2)
        self.Label6_2 = QtGui.QLabel(self.formLayoutWidget_2)
        self.Label6_2.setObjectName(_fromUtf8("Label6_2"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.LabelRole, self.Label6_2)
        self.DoubleSpinBox5_2 = QtGui.QDoubleSpinBox(self.formLayoutWidget_2)
        self.DoubleSpinBox5_2.setEnabled(False)
        self.DoubleSpinBox5_2.setDecimals(3)
        self.DoubleSpinBox5_2.setMinimum(-9999.0)
        self.DoubleSpinBox5_2.setMaximum(9999.0)
        self.DoubleSpinBox5_2.setObjectName(_fromUtf8("DoubleSpinBox5_2"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox5_2)
        self.Label4_3 = QtGui.QLabel(self.formLayoutWidget_2)
        self.Label4_3.setObjectName(_fromUtf8("Label4_3"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.Label4_3)
        self.formLayoutWidget_3 = QtGui.QWidget(self.tab_3)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(690, 60, 188, 31))
        self.formLayoutWidget_3.setObjectName(_fromUtf8("formLayoutWidget_3"))
        self.formLayout_4 = QtGui.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setMargin(0)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.Label14 = QtGui.QLabel(self.formLayoutWidget_3)
        self.Label14.setObjectName(_fromUtf8("Label14"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.Label14)
        self.DoubleSpinBox14 = QtGui.QDoubleSpinBox(self.formLayoutWidget_3)
        self.DoubleSpinBox14.setDecimals(3)
        self.DoubleSpinBox14.setMinimum(-9999.0)
        self.DoubleSpinBox14.setMaximum(9999.0)
        self.DoubleSpinBox14.setObjectName(_fromUtf8("DoubleSpinBox14"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox14)
        self.formLayoutWidget_4 = QtGui.QWidget(self.tab_3)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(690, 240, 261, 152))
        self.formLayoutWidget_4.setObjectName(_fromUtf8("formLayoutWidget_4"))
        self.formLayout_5 = QtGui.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setMargin(0)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.label15 = QtGui.QLabel(self.formLayoutWidget_4)
        self.label15.setObjectName(_fromUtf8("label15"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label15)
        self.DoubleSpinBox15 = QtGui.QDoubleSpinBox(self.formLayoutWidget_4)
        self.DoubleSpinBox15.setDecimals(3)
        self.DoubleSpinBox15.setMinimum(-9999.0)
        self.DoubleSpinBox15.setMaximum(9999.0)
        self.DoubleSpinBox15.setObjectName(_fromUtf8("DoubleSpinBox15"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox15)
        self.Label16 = QtGui.QLabel(self.formLayoutWidget_4)
        self.Label16.setObjectName(_fromUtf8("Label16"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.Label16)
        self.DoubleSpinBox16 = QtGui.QDoubleSpinBox(self.formLayoutWidget_4)
        self.DoubleSpinBox16.setDecimals(3)
        self.DoubleSpinBox16.setMinimum(-9999.0)
        self.DoubleSpinBox16.setMaximum(9999.0)
        self.DoubleSpinBox16.setObjectName(_fromUtf8("DoubleSpinBox16"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox16)
        self.Label17 = QtGui.QLabel(self.formLayoutWidget_4)
        self.Label17.setObjectName(_fromUtf8("Label17"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.Label17)
        self.DoubleSpinBox17 = QtGui.QDoubleSpinBox(self.formLayoutWidget_4)
        self.DoubleSpinBox17.setDecimals(3)
        self.DoubleSpinBox17.setMinimum(-9999.0)
        self.DoubleSpinBox17.setMaximum(9999.0)
        self.DoubleSpinBox17.setObjectName(_fromUtf8("DoubleSpinBox17"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox17)
        self.Label18 = QtGui.QLabel(self.formLayoutWidget_4)
        self.Label18.setObjectName(_fromUtf8("Label18"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.LabelRole, self.Label18)
        self.DoubleSpinBox18 = QtGui.QDoubleSpinBox(self.formLayoutWidget_4)
        self.DoubleSpinBox18.setDecimals(3)
        self.DoubleSpinBox18.setMinimum(-9999.0)
        self.DoubleSpinBox18.setMaximum(9999.0)
        self.DoubleSpinBox18.setObjectName(_fromUtf8("DoubleSpinBox18"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox18)
        self.Label19 = QtGui.QLabel(self.formLayoutWidget_4)
        self.Label19.setObjectName(_fromUtf8("Label19"))
        self.formLayout_5.setWidget(4, QtGui.QFormLayout.LabelRole, self.Label19)
        self.Label20 = QtGui.QLabel(self.formLayoutWidget_4)
        self.Label20.setObjectName(_fromUtf8("Label20"))
        self.formLayout_5.setWidget(5, QtGui.QFormLayout.LabelRole, self.Label20)
        self.DoubleSpinBox20 = QtGui.QDoubleSpinBox(self.formLayoutWidget_4)
        self.DoubleSpinBox20.setDecimals(3)
        self.DoubleSpinBox20.setMinimum(-9999.0)
        self.DoubleSpinBox20.setMaximum(9999.0)
        self.DoubleSpinBox20.setObjectName(_fromUtf8("DoubleSpinBox20"))
        self.formLayout_5.setWidget(5, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox20)
        self.DoubleSpinBox19 = QtGui.QDoubleSpinBox(self.formLayoutWidget_4)
        self.DoubleSpinBox19.setDecimals(3)
        self.DoubleSpinBox19.setMinimum(-9999.0)
        self.DoubleSpinBox19.setMaximum(9999.0)
        self.DoubleSpinBox19.setObjectName(_fromUtf8("DoubleSpinBox19"))
        self.formLayout_5.setWidget(4, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox19)
        self.label_15 = QtGui.QLabel(self.tab_3)
        self.label_15.setGeometry(QtCore.QRect(30, 30, 54, 12))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.tab_3)
        self.label_16.setGeometry(QtCore.QRect(300, 30, 54, 12))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.tab_3)
        self.label_17.setGeometry(QtCore.QRect(690, 30, 54, 12))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.tab_3)
        self.label_18.setGeometry(QtCore.QRect(690, 200, 161, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.pushButton_13 = QtGui.QPushButton(self.tab_3)
        self.pushButton_13.setGeometry(QtCore.QRect(340, 440, 151, 23))
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.verticalLayoutWidget = QtGui.QWidget(self.tab_3)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(220, 60, 31, 341))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_21 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.verticalLayout.addWidget(self.label_21)
        self.label_20 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout.addWidget(self.label_20)
        self.label_19 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout.addWidget(self.label_19)
        self.label_22 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.verticalLayout.addWidget(self.label_22)
        self.label_24 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.verticalLayout.addWidget(self.label_24)
        self.label_23 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.verticalLayout.addWidget(self.label_23)
        self.label_25 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.verticalLayout.addWidget(self.label_25)
        self.label_26 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.verticalLayout.addWidget(self.label_26)
        self.label_27 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.verticalLayout.addWidget(self.label_27)
        self.label_28 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_28.setText(_fromUtf8(""))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.verticalLayout.addWidget(self.label_28)
        self.label_29 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_29.setText(_fromUtf8(""))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.verticalLayout.addWidget(self.label_29)
        self.label_30 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_30.setText(_fromUtf8(""))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.verticalLayout.addWidget(self.label_30)
        self.label_31 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_31.setText(_fromUtf8(""))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.verticalLayout.addWidget(self.label_31)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.tab_3)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(620, 60, 31, 341))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_32 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.verticalLayout_2.addWidget(self.label_32)
        self.label_33 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.verticalLayout_2.addWidget(self.label_33)
        self.label_34 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.verticalLayout_2.addWidget(self.label_34)
        self.label_35 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.verticalLayout_2.addWidget(self.label_35)
        self.label_36 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.verticalLayout_2.addWidget(self.label_36)
        self.label_37 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.verticalLayout_2.addWidget(self.label_37)
        self.label_38 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.verticalLayout_2.addWidget(self.label_38)
        self.label_39 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_39.setText(_fromUtf8(""))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.verticalLayout_2.addWidget(self.label_39)
        self.label_40 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.verticalLayout_2.addWidget(self.label_40)
        self.label_41 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.verticalLayout_2.addWidget(self.label_41)
        self.label_42 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.verticalLayout_2.addWidget(self.label_42)
        self.label_43 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.verticalLayout_2.addWidget(self.label_43)
        self.label_44 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.verticalLayout_2.addWidget(self.label_44)
        self.pushButton_14 = QtGui.QPushButton(self.tab_3)
        self.pushButton_14.setGeometry(QtCore.QRect(740, 440, 151, 23))
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.groupBox = QtGui.QGroupBox(self.tab_4)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 461, 671))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayoutWidget_6 = QtGui.QWidget(self.groupBox)
        self.formLayoutWidget_6.setGeometry(QtCore.QRect(213, 40, 242, 271))
        self.formLayoutWidget_6.setObjectName(_fromUtf8("formLayoutWidget_6"))
        self.formLayout_7 = QtGui.QFormLayout(self.formLayoutWidget_6)
        self.formLayout_7.setMargin(0)
        self.formLayout_7.setObjectName(_fromUtf8("formLayout_7"))
        self.Label_14 = QtGui.QLabel(self.formLayoutWidget_6)
        self.Label_14.setObjectName(_fromUtf8("Label_14"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.LabelRole, self.Label_14)
        self.DoubleSpinBox1_4 = QtGui.QDoubleSpinBox(self.formLayoutWidget_6)
        self.DoubleSpinBox1_4.setDecimals(3)
        self.DoubleSpinBox1_4.setMinimum(-9999.0)
        self.DoubleSpinBox1_4.setMaximum(99999.0)
        self.DoubleSpinBox1_4.setObjectName(_fromUtf8("DoubleSpinBox1_4"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox1_4)
        self.Label_15 = QtGui.QLabel(self.formLayoutWidget_6)
        self.Label_15.setObjectName(_fromUtf8("Label_15"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.LabelRole, self.Label_15)
        self.DoubleSpinBox2_4 = QtGui.QDoubleSpinBox(self.formLayoutWidget_6)
        self.DoubleSpinBox2_4.setDecimals(3)
        self.DoubleSpinBox2_4.setMinimum(-9999.0)
        self.DoubleSpinBox2_4.setMaximum(99999.0)
        self.DoubleSpinBox2_4.setObjectName(_fromUtf8("DoubleSpinBox2_4"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox2_4)
        self.Label_16 = QtGui.QLabel(self.formLayoutWidget_6)
        self.Label_16.setObjectName(_fromUtf8("Label_16"))
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.LabelRole, self.Label_16)
        self.DoubleSpinBox3_4 = QtGui.QDoubleSpinBox(self.formLayoutWidget_6)
        self.DoubleSpinBox3_4.setDecimals(3)
        self.DoubleSpinBox3_4.setMinimum(-9999.0)
        self.DoubleSpinBox3_4.setMaximum(99999.0)
        self.DoubleSpinBox3_4.setObjectName(_fromUtf8("DoubleSpinBox3_4"))
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox3_4)
        self.Label_17 = QtGui.QLabel(self.formLayoutWidget_6)
        self.Label_17.setObjectName(_fromUtf8("Label_17"))
        self.formLayout_7.setWidget(3, QtGui.QFormLayout.LabelRole, self.Label_17)
        self.DoubleSpinBox4_4 = QtGui.QDoubleSpinBox(self.formLayoutWidget_6)
        self.DoubleSpinBox4_4.setDecimals(3)
        self.DoubleSpinBox4_4.setMinimum(-9999.0)
        self.DoubleSpinBox4_4.setMaximum(99999.0)
        self.DoubleSpinBox4_4.setObjectName(_fromUtf8("DoubleSpinBox4_4"))
        self.formLayout_7.setWidget(3, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox4_4)
        self.Label_18 = QtGui.QLabel(self.formLayoutWidget_6)
        self.Label_18.setObjectName(_fromUtf8("Label_18"))
        self.formLayout_7.setWidget(4, QtGui.QFormLayout.LabelRole, self.Label_18)
        self.DoubleSpinBox5_4 = QtGui.QDoubleSpinBox(self.formLayoutWidget_6)
        self.DoubleSpinBox5_4.setDecimals(3)
        self.DoubleSpinBox5_4.setMinimum(-9999.0)
        self.DoubleSpinBox5_4.setMaximum(99999.0)
        self.DoubleSpinBox5_4.setObjectName(_fromUtf8("DoubleSpinBox5_4"))
        self.formLayout_7.setWidget(4, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox5_4)
        self.Label_19 = QtGui.QLabel(self.formLayoutWidget_6)
        self.Label_19.setObjectName(_fromUtf8("Label_19"))
        self.formLayout_7.setWidget(5, QtGui.QFormLayout.LabelRole, self.Label_19)
        self.DoubleSpinBox6_4 = QtGui.QDoubleSpinBox(self.formLayoutWidget_6)
        self.DoubleSpinBox6_4.setDecimals(3)
        self.DoubleSpinBox6_4.setMinimum(-9999.0)
        self.DoubleSpinBox6_4.setMaximum(99999.0)
        self.DoubleSpinBox6_4.setObjectName(_fromUtf8("DoubleSpinBox6_4"))
        self.formLayout_7.setWidget(5, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox6_4)
        self.Label_20 = QtGui.QLabel(self.formLayoutWidget_6)
        self.Label_20.setObjectName(_fromUtf8("Label_20"))
        self.formLayout_7.setWidget(6, QtGui.QFormLayout.LabelRole, self.Label_20)
        self.DoubleSpinBox7_4 = QtGui.QDoubleSpinBox(self.formLayoutWidget_6)
        self.DoubleSpinBox7_4.setDecimals(3)
        self.DoubleSpinBox7_4.setMinimum(-9999.0)
        self.DoubleSpinBox7_4.setMaximum(99999.0)
        self.DoubleSpinBox7_4.setObjectName(_fromUtf8("DoubleSpinBox7_4"))
        self.formLayout_7.setWidget(6, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox7_4)
        self.Label_21 = QtGui.QLabel(self.formLayoutWidget_6)
        self.Label_21.setObjectName(_fromUtf8("Label_21"))
        self.formLayout_7.setWidget(7, QtGui.QFormLayout.LabelRole, self.Label_21)
        self.Label_22 = QtGui.QLabel(self.formLayoutWidget_6)
        self.Label_22.setObjectName(_fromUtf8("Label_22"))
        self.formLayout_7.setWidget(8, QtGui.QFormLayout.LabelRole, self.Label_22)
        self.DoubleSpinBox9_4 = QtGui.QDoubleSpinBox(self.formLayoutWidget_6)
        self.DoubleSpinBox9_4.setDecimals(3)
        self.DoubleSpinBox9_4.setMinimum(-9999.0)
        self.DoubleSpinBox9_4.setMaximum(99999.0)
        self.DoubleSpinBox9_4.setObjectName(_fromUtf8("DoubleSpinBox9_4"))
        self.formLayout_7.setWidget(8, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox9_4)
        self.DoubleSpinBox8_4 = QtGui.QDoubleSpinBox(self.formLayoutWidget_6)
        self.DoubleSpinBox8_4.setDecimals(3)
        self.DoubleSpinBox8_4.setMinimum(-9999.0)
        self.DoubleSpinBox8_4.setMaximum(99999.0)
        self.DoubleSpinBox8_4.setObjectName(_fromUtf8("DoubleSpinBox8_4"))
        self.formLayout_7.setWidget(7, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox8_4)
        self.formLayoutWidget_5 = QtGui.QWidget(self.groupBox)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(10, 40, 182, 334))
        self.formLayoutWidget_5.setObjectName(_fromUtf8("formLayoutWidget_5"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget_5)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.Label = QtGui.QLabel(self.formLayoutWidget_5)
        self.Label.setObjectName(_fromUtf8("Label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.Label)
        self.DoubleSpinBox1_3 = QtGui.QDoubleSpinBox(self.formLayoutWidget_5)
        self.DoubleSpinBox1_3.setDecimals(3)
        self.DoubleSpinBox1_3.setMinimum(-9999.0)
        self.DoubleSpinBox1_3.setMaximum(99999.0)
        self.DoubleSpinBox1_3.setProperty("value", 26.0)
        self.DoubleSpinBox1_3.setObjectName(_fromUtf8("DoubleSpinBox1_3"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox1_3)
        self.Label_2 = QtGui.QLabel(self.formLayoutWidget_5)
        self.Label_2.setObjectName(_fromUtf8("Label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.Label_2)
        self.DoubleSpinBox2_3 = QtGui.QDoubleSpinBox(self.formLayoutWidget_5)
        self.DoubleSpinBox2_3.setEnabled(False)
        self.DoubleSpinBox2_3.setDecimals(3)
        self.DoubleSpinBox2_3.setMinimum(-9999.0)
        self.DoubleSpinBox2_3.setMaximum(99999.0)
        self.DoubleSpinBox2_3.setObjectName(_fromUtf8("DoubleSpinBox2_3"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox2_3)
        self.Label_3 = QtGui.QLabel(self.formLayoutWidget_5)
        self.Label_3.setObjectName(_fromUtf8("Label_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.Label_3)
        self.DoubleSpinBox3_3 = QtGui.QDoubleSpinBox(self.formLayoutWidget_5)
        self.DoubleSpinBox3_3.setEnabled(False)
        self.DoubleSpinBox3_3.setDecimals(3)
        self.DoubleSpinBox3_3.setMinimum(-9999.0)
        self.DoubleSpinBox3_3.setMaximum(99999.0)
        self.DoubleSpinBox3_3.setObjectName(_fromUtf8("DoubleSpinBox3_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox3_3)
        self.Label_4 = QtGui.QLabel(self.formLayoutWidget_5)
        self.Label_4.setObjectName(_fromUtf8("Label_4"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.Label_4)
        self.DoubleSpinBox4_3 = QtGui.QDoubleSpinBox(self.formLayoutWidget_5)
        self.DoubleSpinBox4_3.setDecimals(3)
        self.DoubleSpinBox4_3.setMinimum(-9999.0)
        self.DoubleSpinBox4_3.setMaximum(99999.0)
        self.DoubleSpinBox4_3.setProperty("value", 502.0)
        self.DoubleSpinBox4_3.setObjectName(_fromUtf8("DoubleSpinBox4_3"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox4_3)
        self.Label_5 = QtGui.QLabel(self.formLayoutWidget_5)
        self.Label_5.setObjectName(_fromUtf8("Label_5"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.Label_5)
        self.DoubleSpinBox5_3 = QtGui.QDoubleSpinBox(self.formLayoutWidget_5)
        self.DoubleSpinBox5_3.setEnabled(False)
        self.DoubleSpinBox5_3.setDecimals(3)
        self.DoubleSpinBox5_3.setMinimum(-9999.0)
        self.DoubleSpinBox5_3.setMaximum(99999.0)
        self.DoubleSpinBox5_3.setObjectName(_fromUtf8("DoubleSpinBox5_3"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox5_3)
        self.Label_6 = QtGui.QLabel(self.formLayoutWidget_5)
        self.Label_6.setObjectName(_fromUtf8("Label_6"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.Label_6)
        self.DoubleSpinBox6_3 = QtGui.QDoubleSpinBox(self.formLayoutWidget_5)
        self.DoubleSpinBox6_3.setDecimals(3)
        self.DoubleSpinBox6_3.setMinimum(-9999.0)
        self.DoubleSpinBox6_3.setMaximum(99999.0)
        self.DoubleSpinBox6_3.setProperty("value", 463.0)
        self.DoubleSpinBox6_3.setObjectName(_fromUtf8("DoubleSpinBox6_3"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox6_3)
        self.Label_7 = QtGui.QLabel(self.formLayoutWidget_5)
        self.Label_7.setObjectName(_fromUtf8("Label_7"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.Label_7)
        self.DoubleSpinBox7_3 = QtGui.QDoubleSpinBox(self.formLayoutWidget_5)
        self.DoubleSpinBox7_3.setEnabled(False)
        self.DoubleSpinBox7_3.setDecimals(3)
        self.DoubleSpinBox7_3.setMinimum(-9999.0)
        self.DoubleSpinBox7_3.setMaximum(99999.0)
        self.DoubleSpinBox7_3.setObjectName(_fromUtf8("DoubleSpinBox7_3"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox7_3)
        self.Label_8 = QtGui.QLabel(self.formLayoutWidget_5)
        self.Label_8.setObjectName(_fromUtf8("Label_8"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.Label_8)
        self.DoubleSpinBox8_3 = QtGui.QDoubleSpinBox(self.formLayoutWidget_5)
        self.DoubleSpinBox8_3.setEnabled(False)
        self.DoubleSpinBox8_3.setDecimals(3)
        self.DoubleSpinBox8_3.setMinimum(-9999.0)
        self.DoubleSpinBox8_3.setMaximum(99999.0)
        self.DoubleSpinBox8_3.setObjectName(_fromUtf8("DoubleSpinBox8_3"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox8_3)
        self.Label_9 = QtGui.QLabel(self.formLayoutWidget_5)
        self.Label_9.setObjectName(_fromUtf8("Label_9"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.Label_9)
        self.DoubleSpinBox9_3 = QtGui.QDoubleSpinBox(self.formLayoutWidget_5)
        self.DoubleSpinBox9_3.setEnabled(False)
        self.DoubleSpinBox9_3.setDecimals(3)
        self.DoubleSpinBox9_3.setMinimum(-9999.0)
        self.DoubleSpinBox9_3.setMaximum(99999.0)
        self.DoubleSpinBox9_3.setObjectName(_fromUtf8("DoubleSpinBox9_3"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox9_3)
        self.Label_10 = QtGui.QLabel(self.formLayoutWidget_5)
        self.Label_10.setObjectName(_fromUtf8("Label_10"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.Label_10)
        self.DoubleSpinBox10_3 = QtGui.QDoubleSpinBox(self.formLayoutWidget_5)
        self.DoubleSpinBox10_3.setEnabled(False)
        self.DoubleSpinBox10_3.setDecimals(3)
        self.DoubleSpinBox10_3.setMinimum(-9999.0)
        self.DoubleSpinBox10_3.setMaximum(99999.0)
        self.DoubleSpinBox10_3.setObjectName(_fromUtf8("DoubleSpinBox10_3"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox10_3)
        self.Label_11 = QtGui.QLabel(self.formLayoutWidget_5)
        self.Label_11.setObjectName(_fromUtf8("Label_11"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.Label_11)
        self.DoubleSpinBox11_3 = QtGui.QDoubleSpinBox(self.formLayoutWidget_5)
        self.DoubleSpinBox11_3.setEnabled(False)
        self.DoubleSpinBox11_3.setDecimals(3)
        self.DoubleSpinBox11_3.setMinimum(-9999.0)
        self.DoubleSpinBox11_3.setMaximum(99999.0)
        self.DoubleSpinBox11_3.setObjectName(_fromUtf8("DoubleSpinBox11_3"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox11_3)
        self.Label_12 = QtGui.QLabel(self.formLayoutWidget_5)
        self.Label_12.setObjectName(_fromUtf8("Label_12"))
        self.formLayout.setWidget(11, QtGui.QFormLayout.LabelRole, self.Label_12)
        self.DoubleSpinBox12_3 = QtGui.QDoubleSpinBox(self.formLayoutWidget_5)
        self.DoubleSpinBox12_3.setEnabled(False)
        self.DoubleSpinBox12_3.setDecimals(3)
        self.DoubleSpinBox12_3.setMinimum(-9999.0)
        self.DoubleSpinBox12_3.setMaximum(99999.0)
        self.DoubleSpinBox12_3.setObjectName(_fromUtf8("DoubleSpinBox12_3"))
        self.formLayout.setWidget(11, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox12_3)
        self.Label_13 = QtGui.QLabel(self.formLayoutWidget_5)
        self.Label_13.setObjectName(_fromUtf8("Label_13"))
        self.formLayout.setWidget(12, QtGui.QFormLayout.LabelRole, self.Label_13)
        self.DoubleSpinBox13_3 = QtGui.QDoubleSpinBox(self.formLayoutWidget_5)
        self.DoubleSpinBox13_3.setEnabled(False)
        self.DoubleSpinBox13_3.setDecimals(3)
        self.DoubleSpinBox13_3.setMinimum(-9999.0)
        self.DoubleSpinBox13_3.setMaximum(99999.0)
        self.DoubleSpinBox13_3.setObjectName(_fromUtf8("DoubleSpinBox13_3"))
        self.formLayout.setWidget(12, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox13_3)
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(70, 420, 371, 211))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.pushButton_7 = QtGui.QPushButton(self.groupBox)
        self.pushButton_7.setGeometry(QtCore.QRect(270, 360, 121, 23))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_2.setGeometry(QtCore.QRect(520, 20, 461, 671))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.formLayoutWidget_9 = QtGui.QWidget(self.groupBox_2)
        self.formLayoutWidget_9.setGeometry(QtCore.QRect(213, 40, 242, 271))
        self.formLayoutWidget_9.setObjectName(_fromUtf8("formLayoutWidget_9"))
        self.formLayout_10 = QtGui.QFormLayout(self.formLayoutWidget_9)
        self.formLayout_10.setMargin(0)
        self.formLayout_10.setObjectName(_fromUtf8("formLayout_10"))
        self.Label_45 = QtGui.QLabel(self.formLayoutWidget_9)
        self.Label_45.setObjectName(_fromUtf8("Label_45"))
        self.formLayout_10.setWidget(0, QtGui.QFormLayout.LabelRole, self.Label_45)
        self.DoubleSpinBox1_7 = QtGui.QDoubleSpinBox(self.formLayoutWidget_9)
        self.DoubleSpinBox1_7.setDecimals(3)
        self.DoubleSpinBox1_7.setMinimum(-9999.0)
        self.DoubleSpinBox1_7.setMaximum(99999.0)
        self.DoubleSpinBox1_7.setObjectName(_fromUtf8("DoubleSpinBox1_7"))
        self.formLayout_10.setWidget(0, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox1_7)
        self.Label_46 = QtGui.QLabel(self.formLayoutWidget_9)
        self.Label_46.setObjectName(_fromUtf8("Label_46"))
        self.formLayout_10.setWidget(1, QtGui.QFormLayout.LabelRole, self.Label_46)
        self.DoubleSpinBox2_7 = QtGui.QDoubleSpinBox(self.formLayoutWidget_9)
        self.DoubleSpinBox2_7.setDecimals(3)
        self.DoubleSpinBox2_7.setMinimum(-9999.0)
        self.DoubleSpinBox2_7.setMaximum(99999.0)
        self.DoubleSpinBox2_7.setObjectName(_fromUtf8("DoubleSpinBox2_7"))
        self.formLayout_10.setWidget(1, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox2_7)
        self.Label_47 = QtGui.QLabel(self.formLayoutWidget_9)
        self.Label_47.setObjectName(_fromUtf8("Label_47"))
        self.formLayout_10.setWidget(2, QtGui.QFormLayout.LabelRole, self.Label_47)
        self.DoubleSpinBox3_7 = QtGui.QDoubleSpinBox(self.formLayoutWidget_9)
        self.DoubleSpinBox3_7.setDecimals(3)
        self.DoubleSpinBox3_7.setMinimum(-9999.0)
        self.DoubleSpinBox3_7.setMaximum(99999.0)
        self.DoubleSpinBox3_7.setObjectName(_fromUtf8("DoubleSpinBox3_7"))
        self.formLayout_10.setWidget(2, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox3_7)
        self.Label_48 = QtGui.QLabel(self.formLayoutWidget_9)
        self.Label_48.setObjectName(_fromUtf8("Label_48"))
        self.formLayout_10.setWidget(3, QtGui.QFormLayout.LabelRole, self.Label_48)
        self.DoubleSpinBox4_7 = QtGui.QDoubleSpinBox(self.formLayoutWidget_9)
        self.DoubleSpinBox4_7.setDecimals(3)
        self.DoubleSpinBox4_7.setMinimum(-9999.0)
        self.DoubleSpinBox4_7.setMaximum(99999.0)
        self.DoubleSpinBox4_7.setObjectName(_fromUtf8("DoubleSpinBox4_7"))
        self.formLayout_10.setWidget(3, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox4_7)
        self.Label_49 = QtGui.QLabel(self.formLayoutWidget_9)
        self.Label_49.setObjectName(_fromUtf8("Label_49"))
        self.formLayout_10.setWidget(4, QtGui.QFormLayout.LabelRole, self.Label_49)
        self.DoubleSpinBox5_7 = QtGui.QDoubleSpinBox(self.formLayoutWidget_9)
        self.DoubleSpinBox5_7.setDecimals(3)
        self.DoubleSpinBox5_7.setMinimum(-9999.0)
        self.DoubleSpinBox5_7.setMaximum(99999.0)
        self.DoubleSpinBox5_7.setObjectName(_fromUtf8("DoubleSpinBox5_7"))
        self.formLayout_10.setWidget(4, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox5_7)
        self.Label_50 = QtGui.QLabel(self.formLayoutWidget_9)
        self.Label_50.setObjectName(_fromUtf8("Label_50"))
        self.formLayout_10.setWidget(5, QtGui.QFormLayout.LabelRole, self.Label_50)
        self.DoubleSpinBox6_7 = QtGui.QDoubleSpinBox(self.formLayoutWidget_9)
        self.DoubleSpinBox6_7.setDecimals(3)
        self.DoubleSpinBox6_7.setMinimum(-9999.0)
        self.DoubleSpinBox6_7.setMaximum(99999.0)
        self.DoubleSpinBox6_7.setObjectName(_fromUtf8("DoubleSpinBox6_7"))
        self.formLayout_10.setWidget(5, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox6_7)
        self.Label_51 = QtGui.QLabel(self.formLayoutWidget_9)
        self.Label_51.setObjectName(_fromUtf8("Label_51"))
        self.formLayout_10.setWidget(6, QtGui.QFormLayout.LabelRole, self.Label_51)
        self.DoubleSpinBox7_7 = QtGui.QDoubleSpinBox(self.formLayoutWidget_9)
        self.DoubleSpinBox7_7.setDecimals(3)
        self.DoubleSpinBox7_7.setMinimum(-9999.0)
        self.DoubleSpinBox7_7.setMaximum(99999.0)
        self.DoubleSpinBox7_7.setObjectName(_fromUtf8("DoubleSpinBox7_7"))
        self.formLayout_10.setWidget(6, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox7_7)
        self.Label_52 = QtGui.QLabel(self.formLayoutWidget_9)
        self.Label_52.setObjectName(_fromUtf8("Label_52"))
        self.formLayout_10.setWidget(7, QtGui.QFormLayout.LabelRole, self.Label_52)
        self.Label_53 = QtGui.QLabel(self.formLayoutWidget_9)
        self.Label_53.setObjectName(_fromUtf8("Label_53"))
        self.formLayout_10.setWidget(8, QtGui.QFormLayout.LabelRole, self.Label_53)
        self.DoubleSpinBox9_7 = QtGui.QDoubleSpinBox(self.formLayoutWidget_9)
        self.DoubleSpinBox9_7.setDecimals(3)
        self.DoubleSpinBox9_7.setMinimum(-9999.0)
        self.DoubleSpinBox9_7.setMaximum(99999.0)
        self.DoubleSpinBox9_7.setObjectName(_fromUtf8("DoubleSpinBox9_7"))
        self.formLayout_10.setWidget(8, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox9_7)
        self.DoubleSpinBox8_7 = QtGui.QDoubleSpinBox(self.formLayoutWidget_9)
        self.DoubleSpinBox8_7.setDecimals(3)
        self.DoubleSpinBox8_7.setMinimum(-9999.0)
        self.DoubleSpinBox8_7.setMaximum(99999.0)
        self.DoubleSpinBox8_7.setObjectName(_fromUtf8("DoubleSpinBox8_7"))
        self.formLayout_10.setWidget(7, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox8_7)
        self.formLayoutWidget_10 = QtGui.QWidget(self.groupBox_2)
        self.formLayoutWidget_10.setGeometry(QtCore.QRect(10, 40, 182, 334))
        self.formLayoutWidget_10.setObjectName(_fromUtf8("formLayoutWidget_10"))
        self.formLayout_11 = QtGui.QFormLayout(self.formLayoutWidget_10)
        self.formLayout_11.setMargin(0)
        self.formLayout_11.setObjectName(_fromUtf8("formLayout_11"))
        self.Label_54 = QtGui.QLabel(self.formLayoutWidget_10)
        self.Label_54.setObjectName(_fromUtf8("Label_54"))
        self.formLayout_11.setWidget(0, QtGui.QFormLayout.LabelRole, self.Label_54)
        self.DoubleSpinBox1_8 = QtGui.QDoubleSpinBox(self.formLayoutWidget_10)
        self.DoubleSpinBox1_8.setDecimals(3)
        self.DoubleSpinBox1_8.setMinimum(-9999.0)
        self.DoubleSpinBox1_8.setMaximum(99999.0)
        self.DoubleSpinBox1_8.setProperty("value", 55.0)
        self.DoubleSpinBox1_8.setObjectName(_fromUtf8("DoubleSpinBox1_8"))
        self.formLayout_11.setWidget(0, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox1_8)
        self.Label_55 = QtGui.QLabel(self.formLayoutWidget_10)
        self.Label_55.setObjectName(_fromUtf8("Label_55"))
        self.formLayout_11.setWidget(1, QtGui.QFormLayout.LabelRole, self.Label_55)
        self.DoubleSpinBox2_8 = QtGui.QDoubleSpinBox(self.formLayoutWidget_10)
        self.DoubleSpinBox2_8.setEnabled(False)
        self.DoubleSpinBox2_8.setDecimals(3)
        self.DoubleSpinBox2_8.setMinimum(-9999.0)
        self.DoubleSpinBox2_8.setMaximum(99999.0)
        self.DoubleSpinBox2_8.setObjectName(_fromUtf8("DoubleSpinBox2_8"))
        self.formLayout_11.setWidget(1, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox2_8)
        self.Label_56 = QtGui.QLabel(self.formLayoutWidget_10)
        self.Label_56.setObjectName(_fromUtf8("Label_56"))
        self.formLayout_11.setWidget(2, QtGui.QFormLayout.LabelRole, self.Label_56)
        self.DoubleSpinBox3_8 = QtGui.QDoubleSpinBox(self.formLayoutWidget_10)
        self.DoubleSpinBox3_8.setEnabled(False)
        self.DoubleSpinBox3_8.setDecimals(3)
        self.DoubleSpinBox3_8.setMinimum(-9999.0)
        self.DoubleSpinBox3_8.setMaximum(99999.0)
        self.DoubleSpinBox3_8.setObjectName(_fromUtf8("DoubleSpinBox3_8"))
        self.formLayout_11.setWidget(2, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox3_8)
        self.Label_57 = QtGui.QLabel(self.formLayoutWidget_10)
        self.Label_57.setObjectName(_fromUtf8("Label_57"))
        self.formLayout_11.setWidget(3, QtGui.QFormLayout.LabelRole, self.Label_57)
        self.DoubleSpinBox4_8 = QtGui.QDoubleSpinBox(self.formLayoutWidget_10)
        self.DoubleSpinBox4_8.setDecimals(3)
        self.DoubleSpinBox4_8.setMinimum(-9999.0)
        self.DoubleSpinBox4_8.setMaximum(99999.0)
        self.DoubleSpinBox4_8.setProperty("value", 2.94)
        self.DoubleSpinBox4_8.setObjectName(_fromUtf8("DoubleSpinBox4_8"))
        self.formLayout_11.setWidget(3, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox4_8)
        self.Label_58 = QtGui.QLabel(self.formLayoutWidget_10)
        self.Label_58.setObjectName(_fromUtf8("Label_58"))
        self.formLayout_11.setWidget(4, QtGui.QFormLayout.LabelRole, self.Label_58)
        self.DoubleSpinBox5_8 = QtGui.QDoubleSpinBox(self.formLayoutWidget_10)
        self.DoubleSpinBox5_8.setEnabled(False)
        self.DoubleSpinBox5_8.setDecimals(3)
        self.DoubleSpinBox5_8.setMinimum(-9999.0)
        self.DoubleSpinBox5_8.setMaximum(99999.0)
        self.DoubleSpinBox5_8.setObjectName(_fromUtf8("DoubleSpinBox5_8"))
        self.formLayout_11.setWidget(4, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox5_8)
        self.Label_59 = QtGui.QLabel(self.formLayoutWidget_10)
        self.Label_59.setObjectName(_fromUtf8("Label_59"))
        self.formLayout_11.setWidget(5, QtGui.QFormLayout.LabelRole, self.Label_59)
        self.DoubleSpinBox6_8 = QtGui.QDoubleSpinBox(self.formLayoutWidget_10)
        self.DoubleSpinBox6_8.setDecimals(3)
        self.DoubleSpinBox6_8.setMinimum(-9999.0)
        self.DoubleSpinBox6_8.setMaximum(99999.0)
        self.DoubleSpinBox6_8.setProperty("value", 1.54)
        self.DoubleSpinBox6_8.setObjectName(_fromUtf8("DoubleSpinBox6_8"))
        self.formLayout_11.setWidget(5, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox6_8)
        self.Label_60 = QtGui.QLabel(self.formLayoutWidget_10)
        self.Label_60.setObjectName(_fromUtf8("Label_60"))
        self.formLayout_11.setWidget(6, QtGui.QFormLayout.LabelRole, self.Label_60)
        self.DoubleSpinBox7_8 = QtGui.QDoubleSpinBox(self.formLayoutWidget_10)
        self.DoubleSpinBox7_8.setEnabled(False)
        self.DoubleSpinBox7_8.setDecimals(3)
        self.DoubleSpinBox7_8.setMinimum(-9999.0)
        self.DoubleSpinBox7_8.setMaximum(99999.0)
        self.DoubleSpinBox7_8.setObjectName(_fromUtf8("DoubleSpinBox7_8"))
        self.formLayout_11.setWidget(6, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox7_8)
        self.Label_61 = QtGui.QLabel(self.formLayoutWidget_10)
        self.Label_61.setObjectName(_fromUtf8("Label_61"))
        self.formLayout_11.setWidget(7, QtGui.QFormLayout.LabelRole, self.Label_61)
        self.DoubleSpinBox8_8 = QtGui.QDoubleSpinBox(self.formLayoutWidget_10)
        self.DoubleSpinBox8_8.setEnabled(False)
        self.DoubleSpinBox8_8.setDecimals(3)
        self.DoubleSpinBox8_8.setMinimum(-9999.0)
        self.DoubleSpinBox8_8.setMaximum(99999.0)
        self.DoubleSpinBox8_8.setObjectName(_fromUtf8("DoubleSpinBox8_8"))
        self.formLayout_11.setWidget(7, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox8_8)
        self.Label_62 = QtGui.QLabel(self.formLayoutWidget_10)
        self.Label_62.setObjectName(_fromUtf8("Label_62"))
        self.formLayout_11.setWidget(8, QtGui.QFormLayout.LabelRole, self.Label_62)
        self.DoubleSpinBox9_8 = QtGui.QDoubleSpinBox(self.formLayoutWidget_10)
        self.DoubleSpinBox9_8.setEnabled(False)
        self.DoubleSpinBox9_8.setDecimals(3)
        self.DoubleSpinBox9_8.setMinimum(-9999.0)
        self.DoubleSpinBox9_8.setMaximum(99999.0)
        self.DoubleSpinBox9_8.setObjectName(_fromUtf8("DoubleSpinBox9_8"))
        self.formLayout_11.setWidget(8, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox9_8)
        self.Label_63 = QtGui.QLabel(self.formLayoutWidget_10)
        self.Label_63.setObjectName(_fromUtf8("Label_63"))
        self.formLayout_11.setWidget(9, QtGui.QFormLayout.LabelRole, self.Label_63)
        self.DoubleSpinBox10_8 = QtGui.QDoubleSpinBox(self.formLayoutWidget_10)
        self.DoubleSpinBox10_8.setEnabled(False)
        self.DoubleSpinBox10_8.setDecimals(3)
        self.DoubleSpinBox10_8.setMinimum(-9999.0)
        self.DoubleSpinBox10_8.setMaximum(99999.0)
        self.DoubleSpinBox10_8.setObjectName(_fromUtf8("DoubleSpinBox10_8"))
        self.formLayout_11.setWidget(9, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox10_8)
        self.Label_64 = QtGui.QLabel(self.formLayoutWidget_10)
        self.Label_64.setObjectName(_fromUtf8("Label_64"))
        self.formLayout_11.setWidget(10, QtGui.QFormLayout.LabelRole, self.Label_64)
        self.DoubleSpinBox11_8 = QtGui.QDoubleSpinBox(self.formLayoutWidget_10)
        self.DoubleSpinBox11_8.setEnabled(False)
        self.DoubleSpinBox11_8.setDecimals(3)
        self.DoubleSpinBox11_8.setMinimum(-9999.0)
        self.DoubleSpinBox11_8.setMaximum(99999.0)
        self.DoubleSpinBox11_8.setObjectName(_fromUtf8("DoubleSpinBox11_8"))
        self.formLayout_11.setWidget(10, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox11_8)
        self.Label_65 = QtGui.QLabel(self.formLayoutWidget_10)
        self.Label_65.setObjectName(_fromUtf8("Label_65"))
        self.formLayout_11.setWidget(11, QtGui.QFormLayout.LabelRole, self.Label_65)
        self.DoubleSpinBox12_8 = QtGui.QDoubleSpinBox(self.formLayoutWidget_10)
        self.DoubleSpinBox12_8.setEnabled(False)
        self.DoubleSpinBox12_8.setDecimals(3)
        self.DoubleSpinBox12_8.setMinimum(-9999.0)
        self.DoubleSpinBox12_8.setMaximum(99999.0)
        self.DoubleSpinBox12_8.setObjectName(_fromUtf8("DoubleSpinBox12_8"))
        self.formLayout_11.setWidget(11, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox12_8)
        self.Label_66 = QtGui.QLabel(self.formLayoutWidget_10)
        self.Label_66.setObjectName(_fromUtf8("Label_66"))
        self.formLayout_11.setWidget(12, QtGui.QFormLayout.LabelRole, self.Label_66)
        self.DoubleSpinBox13_8 = QtGui.QDoubleSpinBox(self.formLayoutWidget_10)
        self.DoubleSpinBox13_8.setEnabled(False)
        self.DoubleSpinBox13_8.setDecimals(3)
        self.DoubleSpinBox13_8.setMinimum(-9999.0)
        self.DoubleSpinBox13_8.setMaximum(99999.0)
        self.DoubleSpinBox13_8.setObjectName(_fromUtf8("DoubleSpinBox13_8"))
        self.formLayout_11.setWidget(12, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox13_8)
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(70, 420, 371, 211))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.pushButton_9 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_9.setGeometry(QtCore.QRect(270, 360, 121, 23))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.formLayoutWidget_11 = QtGui.QWidget(self.tab_5)
        self.formLayoutWidget_11.setGeometry(QtCore.QRect(60, 80, 225, 141))
        self.formLayoutWidget_11.setObjectName(_fromUtf8("formLayoutWidget_11"))
        self.formLayout_12 = QtGui.QFormLayout(self.formLayoutWidget_11)
        self.formLayout_12.setMargin(0)
        self.formLayout_12.setObjectName(_fromUtf8("formLayout_12"))
        self.Label_67 = QtGui.QLabel(self.formLayoutWidget_11)
        self.Label_67.setObjectName(_fromUtf8("Label_67"))
        self.formLayout_12.setWidget(0, QtGui.QFormLayout.LabelRole, self.Label_67)
        self.DoubleSpinBox1_9 = QtGui.QDoubleSpinBox(self.formLayoutWidget_11)
        self.DoubleSpinBox1_9.setEnabled(False)
        self.DoubleSpinBox1_9.setDecimals(3)
        self.DoubleSpinBox1_9.setMinimum(-9999.0)
        self.DoubleSpinBox1_9.setMaximum(99999.0)
        self.DoubleSpinBox1_9.setObjectName(_fromUtf8("DoubleSpinBox1_9"))
        self.formLayout_12.setWidget(0, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox1_9)
        self.Label_68 = QtGui.QLabel(self.formLayoutWidget_11)
        self.Label_68.setObjectName(_fromUtf8("Label_68"))
        self.formLayout_12.setWidget(1, QtGui.QFormLayout.LabelRole, self.Label_68)
        self.DoubleSpinBox2_9 = QtGui.QDoubleSpinBox(self.formLayoutWidget_11)
        self.DoubleSpinBox2_9.setDecimals(3)
        self.DoubleSpinBox2_9.setMinimum(-9999.0)
        self.DoubleSpinBox2_9.setMaximum(99999.0)
        self.DoubleSpinBox2_9.setProperty("value", 0.75)
        self.DoubleSpinBox2_9.setObjectName(_fromUtf8("DoubleSpinBox2_9"))
        self.formLayout_12.setWidget(1, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox2_9)
        self.Label_69 = QtGui.QLabel(self.formLayoutWidget_11)
        self.Label_69.setObjectName(_fromUtf8("Label_69"))
        self.formLayout_12.setWidget(2, QtGui.QFormLayout.LabelRole, self.Label_69)
        self.DoubleSpinBox3_9 = QtGui.QDoubleSpinBox(self.formLayoutWidget_11)
        self.DoubleSpinBox3_9.setDecimals(3)
        self.DoubleSpinBox3_9.setMinimum(-9999.0)
        self.DoubleSpinBox3_9.setMaximum(99999.0)
        self.DoubleSpinBox3_9.setProperty("value", 4.0)
        self.DoubleSpinBox3_9.setObjectName(_fromUtf8("DoubleSpinBox3_9"))
        self.formLayout_12.setWidget(2, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox3_9)
        self.Label_70 = QtGui.QLabel(self.formLayoutWidget_11)
        self.Label_70.setObjectName(_fromUtf8("Label_70"))
        self.formLayout_12.setWidget(3, QtGui.QFormLayout.LabelRole, self.Label_70)
        self.DoubleSpinBox4_9 = QtGui.QDoubleSpinBox(self.formLayoutWidget_11)
        self.DoubleSpinBox4_9.setEnabled(False)
        self.DoubleSpinBox4_9.setDecimals(3)
        self.DoubleSpinBox4_9.setMinimum(-9999.0)
        self.DoubleSpinBox4_9.setMaximum(99999.0)
        self.DoubleSpinBox4_9.setObjectName(_fromUtf8("DoubleSpinBox4_9"))
        self.formLayout_12.setWidget(3, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox4_9)
        self.Label_71 = QtGui.QLabel(self.formLayoutWidget_11)
        self.Label_71.setObjectName(_fromUtf8("Label_71"))
        self.formLayout_12.setWidget(4, QtGui.QFormLayout.LabelRole, self.Label_71)
        self.DoubleSpinBox5_9 = QtGui.QDoubleSpinBox(self.formLayoutWidget_11)
        self.DoubleSpinBox5_9.setEnabled(False)
        self.DoubleSpinBox5_9.setDecimals(3)
        self.DoubleSpinBox5_9.setMinimum(-9999.0)
        self.DoubleSpinBox5_9.setMaximum(99999.0)
        self.DoubleSpinBox5_9.setObjectName(_fromUtf8("DoubleSpinBox5_9"))
        self.formLayout_12.setWidget(4, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox5_9)
        self.formLayoutWidget_12 = QtGui.QWidget(self.tab_5)
        self.formLayoutWidget_12.setGeometry(QtCore.QRect(370, 80, 242, 80))
        self.formLayoutWidget_12.setObjectName(_fromUtf8("formLayoutWidget_12"))
        self.formLayout_13 = QtGui.QFormLayout(self.formLayoutWidget_12)
        self.formLayout_13.setMargin(0)
        self.formLayout_13.setObjectName(_fromUtf8("formLayout_13"))
        self.Label_72 = QtGui.QLabel(self.formLayoutWidget_12)
        self.Label_72.setObjectName(_fromUtf8("Label_72"))
        self.formLayout_13.setWidget(0, QtGui.QFormLayout.LabelRole, self.Label_72)
        self.DoubleSpinBox1_10 = QtGui.QDoubleSpinBox(self.formLayoutWidget_12)
        self.DoubleSpinBox1_10.setDecimals(3)
        self.DoubleSpinBox1_10.setMinimum(-9999.0)
        self.DoubleSpinBox1_10.setMaximum(99999.0)
        self.DoubleSpinBox1_10.setObjectName(_fromUtf8("DoubleSpinBox1_10"))
        self.formLayout_13.setWidget(0, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox1_10)
        self.Label_73 = QtGui.QLabel(self.formLayoutWidget_12)
        self.Label_73.setObjectName(_fromUtf8("Label_73"))
        self.formLayout_13.setWidget(1, QtGui.QFormLayout.LabelRole, self.Label_73)
        self.DoubleSpinBox2_10 = QtGui.QDoubleSpinBox(self.formLayoutWidget_12)
        self.DoubleSpinBox2_10.setDecimals(3)
        self.DoubleSpinBox2_10.setMinimum(-9999.0)
        self.DoubleSpinBox2_10.setMaximum(99999.0)
        self.DoubleSpinBox2_10.setObjectName(_fromUtf8("DoubleSpinBox2_10"))
        self.formLayout_13.setWidget(1, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox2_10)
        self.Label_74 = QtGui.QLabel(self.formLayoutWidget_12)
        self.Label_74.setObjectName(_fromUtf8("Label_74"))
        self.formLayout_13.setWidget(2, QtGui.QFormLayout.LabelRole, self.Label_74)
        self.DoubleSpinBox3_10 = QtGui.QDoubleSpinBox(self.formLayoutWidget_12)
        self.DoubleSpinBox3_10.setDecimals(3)
        self.DoubleSpinBox3_10.setMinimum(-9999.0)
        self.DoubleSpinBox3_10.setMaximum(99999.0)
        self.DoubleSpinBox3_10.setObjectName(_fromUtf8("DoubleSpinBox3_10"))
        self.formLayout_13.setWidget(2, QtGui.QFormLayout.FieldRole, self.DoubleSpinBox3_10)
        self.label_12 = QtGui.QLabel(self.tab_5)
        self.label_12.setGeometry(QtCore.QRect(60, 40, 71, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.tab_5)
        self.label_13.setGeometry(QtCore.QRect(370, 40, 71, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.pushButton_10 = QtGui.QPushButton(self.tab_5)
        self.pushButton_10.setGeometry(QtCore.QRect(440, 200, 91, 23))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.label_14 = QtGui.QLabel(self.tab_5)
        self.label_14.setGeometry(QtCore.QRect(270, 330, 471, 371))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "挖深式消力池消能设计", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "1", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "闸前水深H", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "闸孔净宽B", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "过闸流量Q", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "动能校正系数α", None))
        item.setToolTip(_translate("Dialog", "一般取1.00~1.05", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "重力加速度g", None))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "流速系数Ψ", None))
        item.setToolTip(_translate("Dialog", "一般取0.95", None))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "消力池首段宽度b1", None))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "消力池末段宽度b2", None))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Dialog", "下游水深hs\'", None))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("Dialog", "淹没系数δ0", None))
        item.setToolTip(_translate("Dialog", "一般取1.05~1.10", None))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("Dialog", "闸底高程H上底", None))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("Dialog", "下游底高程H下底", None))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Dialog", "3.900", None))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("Dialog", "93.500", None))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("Dialog", "1173.300", None))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("Dialog", "1.000", None))
        item = self.tableWidget.item(0, 4)
        item.setText(_translate("Dialog", "9.810", None))
        item = self.tableWidget.item(0, 5)
        item.setText(_translate("Dialog", "0.950", None))
        item = self.tableWidget.item(0, 6)
        item.setText(_translate("Dialog", "111.200", None))
        item = self.tableWidget.item(0, 7)
        item.setText(_translate("Dialog", "111.200", None))
        item = self.tableWidget.item(0, 8)
        item.setText(_translate("Dialog", "2.730", None))
        item = self.tableWidget.item(0, 9)
        item.setText(_translate("Dialog", "1.050", None))
        item = self.tableWidget.item(0, 10)
        item.setText(_translate("Dialog", "111.270", None))
        item = self.tableWidget.item(0, 11)
        item.setText(_translate("Dialog", "110.6", None))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "1", None))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "行进流速V", None))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "单宽流量q", None))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "收缩水深hc", None))
        item.setToolTip(_translate("Dialog", "请试着输入收缩水深，使池深d1和d2相等，此池深即所求消力池池深。（采用单变量求解）", None))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "跃后水深hc\'\'", None))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "出池落差ΔZ", None))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "总势能T0", None))
        item.setToolTip(_translate("Dialog", "消力池底板顶面算起的总势能T0", None))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "计算消力池深d1", None))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "计算消力池深d2", None))
        self.pushButton.setText(_translate("Dialog", "计算消力池深", None))
        self.pushButton_2.setText(_translate("Dialog", "+ 行", None))
        self.pushButton_3.setText(_translate("Dialog", "- 行", None))
        self.label.setText(_translate("Dialog", "确定消力池深设计流量", None))
        self.label_4.setText(_translate("Dialog", "（考虑不同闸孔数泄流时，需分别进行分析，最后取池深最大的情况）", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "确定消力池设计流量", None))
        item = self.tableWidget_3.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "1", None))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "过闸流量Q", None))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "上游水位", None))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "下游水位", None))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Q*ΔH", None))
        __sortingEnabled = self.tableWidget_3.isSortingEnabled()
        self.tableWidget_3.setSortingEnabled(False)
        item = self.tableWidget_3.item(0, 0)
        item.setText(_translate("Dialog", "100", None))
        item = self.tableWidget_3.item(0, 1)
        item.setText(_translate("Dialog", "100", None))
        item = self.tableWidget_3.item(0, 2)
        item.setText(_translate("Dialog", "98.0", None))
        self.tableWidget_3.setSortingEnabled(__sortingEnabled)
        self.pushButton_4.setText(_translate("Dialog", "+ 行", None))
        self.pushButton_5.setText(_translate("Dialog", "- 行", None))
        self.pushButton_6.setText(_translate("Dialog", "计算Q*ΔH", None))
        self.label_2.setText(_translate("Dialog", "确定消力池底板厚、海漫长度设计流量", None))
        self.label_3.setText(_translate("Dialog", "（q*ΔH^0.5最大时，底板厚最大；考虑不同闸孔数泄流时，需分别进行分析，最后取q*ΔH^0.5最大的情况）", None))
        self.label_5.setText(_translate("Dialog", "注：q*ΔH^0.5也就是Q*ΔH最大", None))
        self.label_8.setText(_translate("Dialog", "<html><head/><body><p><img src=\":/images/xlchm.png\"/></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "确定消力池底板厚、海漫长度设计流量", None))
        self.Label1.setText(_translate("Dialog", "<html><head/><body><p>过闸流量 Q</p></body></html>", None))
        self.Label2.setText(_translate("Dialog", "<html><head/><body><p>消力池首宽 b<span style=\" vertical-align:sub;\">1</span></p></body></html>", None))
        self.Label3.setText(_translate("Dialog", "<html><head/><body><p>消力池末宽 b<span style=\" vertical-align:sub;\">2</span></p></body></html>", None))
        self.Label4.setText(_translate("Dialog", "<html><head/><body><p>上游水位 H<span style=\" vertical-align:sub;\">上</span></p></body></html>", None))
        self.Label5.setText(_translate("Dialog", "<html><head/><body><p>闸底板高程 H<span style=\" vertical-align:sub;\">上底</span></p></body></html>", None))
        self.Label6.setText(_translate("Dialog", "<html><head/><body><p>下游水位 H<span style=\" vertical-align:sub;\">下</span></p></body></html>", None))
        self.Label7.setText(_translate("Dialog", "<html><head/><body><p>下游底高程 H<span style=\" vertical-align:sub;\">下底</span></p></body></html>", None))
        self.Label8.setText(_translate("Dialog", "<html><head/><body><p>闸孔总净宽 B<span style=\" vertical-align:sub;\">0</span></p></body></html>", None))
        self.Label9.setText(_translate("Dialog", "<html><head/><body><p>上游河宽宽 B</p></body></html>", None))
        self.Label10.setText(_translate("Dialog", "<html><head/><body><p>重力加速度 g</p></body></html>", None))
        self.Label11.setText(_translate("Dialog", "<html><head/><body><p>流速系数 φ</p></body></html>", None))
        self.Label12.setText(_translate("Dialog", "<html><head/><body><p>水流动能校正系数 α</p></body></html>", None))
        self.Label13.setText(_translate("Dialog", "<html><head/><body><p>水跃淹没系数 σ<span style=\" vertical-align:sub;\">0</span></p></body></html>", None))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p><img src=\":/images/xlccs.png\"/></p></body></html>", None))
        self.label_7.setText(_translate("Dialog", "<html><head/><body><p><img src=\":/images/xlccs_gs.png\"/></p></body></html>", None))
        self.Label1_2.setText(_translate("Dialog", "<html><head/><body><p>单宽流量 q</p></body></html>", None))
        self.Label2_2.setText(_translate("Dialog", "<html><head/><body><p>试输入收缩水深 h<span style=\" vertical-align:sub;\">c</span></p></body></html>", None))
        self.Label3_2.setText(_translate("Dialog", "<html><head/><body><p>上游水深 H</p></body></html>", None))
        self.Label5_2.setText(_translate("Dialog", "临界水深：", None))
        self.Label7_2.setText(_translate("Dialog", "<html><head/><body><p>闸前行进流速 V</p></body></html>", None))
        self.Label8_2.setText(_translate("Dialog", "<html><head/><body><p>跃前断面水流弗劳德数 F<span style=\" vertical-align:sub;\">r</span></p></body></html>", None))
        self.Label9_2.setText(_translate("Dialog", "<html><head/><body><p>消力池底板顶面算起的总势能 T<span style=\" vertical-align:sub;\">0</span></p></body></html>", None))
        self.Label10_2.setText(_translate("Dialog", "<html><head/><body><p>跃后水深 h<span style=\" vertical-align:sub;\">c</span>&quot;</p></body></html>", None))
        self.Label11_2.setText(_translate("Dialog", "<html><head/><body><p>出池落差 ΔZ</p></body></html>", None))
        self.Label12_2.setText(_translate("Dialog", "<html><head/><body><p>消力池深 d1=T<span style=\" vertical-align:sub;\">0</span>-H-αV<span style=\" vertical-align:super;\">2</span>/2g-（H<span style=\" vertical-align:sub;\">上底</span>-H<span style=\" vertical-align:sub;\">下底</span>）</p></body></html>", None))
        self.Label13_2.setText(_translate("Dialog", "<html><head/><body><p>消力池深 d2=σ<span style=\" vertical-align:sub;\">0</span>*hc&quot;-hs\'-△Z</p></body></html>", None))
        self.Label6_2.setText(_translate("Dialog", "<html><head/><body><p>上下游水位差 ΔH</p></body></html>", None))
        self.Label4_3.setText(_translate("Dialog", "<html><head/><body><p>下游水深 h<span style=\" vertical-align:sub;\">s</span>\'</p></body></html>", None))
        self.Label14.setText(_translate("Dialog", "<html><head/><body><p>消力池池深取值 d                       </p></body></html>", None))
        self.label15.setText(_translate("Dialog", "<html><head/><body><p>消力池底板顶面算起的总势能 T<span style=\" vertical-align:sub;\">0</span></p></body></html>", None))
        self.Label16.setText(_translate("Dialog", "<html><head/><body><p>收缩水深 h<span style=\" vertical-align:sub;\">c</span></p></body></html>", None))
        self.Label17.setText(_translate("Dialog", "<html><head/><body><p>跃前断面水流弗劳德数 F<span style=\" vertical-align:sub;\">r</span></p></body></html>", None))
        self.Label18.setText(_translate("Dialog", "<html><head/><body><p>跃后水深 h<span style=\" vertical-align:sub;\">c</span>&quot;</p></body></html>", None))
        self.Label19.setText(_translate("Dialog", "<html><head/><body><p>水跃淹没系数 σ</p></body></html>", None))
        self.Label20.setText(_translate("Dialog", "<html><head/><body><p>低弗劳德数最佳淹没度 σ<span style=\" vertical-align:sub;\">0</span></p></body></html>", None))
        self.label_15.setText(_translate("Dialog", "输入参数", None))
        self.label_16.setText(_translate("Dialog", "计算过程", None))
        self.label_17.setText(_translate("Dialog", "取值", None))
        self.label_18.setText(_translate("Dialog", "验算消力池的水跃淹没系数", None))
        self.pushButton_13.setText(_translate("Dialog", "计算池深", None))
        self.label_21.setText(_translate("Dialog", "<html><head/><body><p>m<span style=\" vertical-align:super;\">3</span>/s</p></body></html>", None))
        self.label_20.setText(_translate("Dialog", "m", None))
        self.label_19.setText(_translate("Dialog", "m", None))
        self.label_22.setText(_translate("Dialog", "m", None))
        self.label_24.setText(_translate("Dialog", "m", None))
        self.label_23.setText(_translate("Dialog", "m", None))
        self.label_25.setText(_translate("Dialog", "m", None))
        self.label_26.setText(_translate("Dialog", "m", None))
        self.label_27.setText(_translate("Dialog", "m", None))
        self.label_32.setText(_translate("Dialog", "<html><head/><body><p>m<span style=\" vertical-align:super;\">3</span>/s</p></body></html>", None))
        self.label_33.setText(_translate("Dialog", "m", None))
        self.label_34.setText(_translate("Dialog", "m", None))
        self.label_35.setText(_translate("Dialog", "m", None))
        self.label_36.setText(_translate("Dialog", "m", None))
        self.label_37.setText(_translate("Dialog", "<html><head/><body><p>m<span style=\" vertical-align:super;\">3</span>/s</p></body></html>", None))
        self.label_38.setText(_translate("Dialog", "m/s", None))
        self.label_40.setText(_translate("Dialog", "m", None))
        self.label_41.setText(_translate("Dialog", "m", None))
        self.label_42.setText(_translate("Dialog", "m", None))
        self.label_43.setText(_translate("Dialog", "m", None))
        self.label_44.setText(_translate("Dialog", "m", None))
        self.pushButton_14.setText(_translate("Dialog", "验算水跃淹没系数", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "挖深式消力池池深计算", None))
        self.groupBox.setTitle(_translate("Dialog", "流量最大设计情况", None))
        self.Label_14.setText(_translate("Dialog", "上游水深", None))
        self.Label_15.setText(_translate("Dialog", "下游水深", None))
        self.Label_16.setText(_translate("Dialog", "上下游水位差", None))
        self.Label_17.setText(_translate("Dialog", "单宽流量", None))
        self.Label_18.setText(_translate("Dialog", "消力池底板顶面算起的总势能", None))
        self.Label_19.setText(_translate("Dialog", "收缩水深", None))
        self.Label_20.setText(_translate("Dialog", "跃前断面水流弗劳德数", None))
        self.Label_21.setText(_translate("Dialog", "跃后水深", None))
        self.Label_22.setText(_translate("Dialog", "水跃淹没系数", None))
        self.Label.setText(_translate("Dialog", "过闸流量", None))
        self.Label_2.setText(_translate("Dialog", "消力池首宽", None))
        self.Label_3.setText(_translate("Dialog", "消力池末宽", None))
        self.Label_4.setText(_translate("Dialog", "上游水位", None))
        self.Label_5.setText(_translate("Dialog", "底板高程", None))
        self.Label_6.setText(_translate("Dialog", "下游水位", None))
        self.Label_7.setText(_translate("Dialog", "下游底高程", None))
        self.Label_8.setText(_translate("Dialog", "上游行进流速", None))
        self.Label_9.setText(_translate("Dialog", "重力加速度", None))
        self.Label_10.setText(_translate("Dialog", "流速系数", None))
        self.Label_11.setText(_translate("Dialog", "水流动能校正系数", None))
        self.Label_12.setText(_translate("Dialog", "闸孔总净宽", None))
        self.Label_13.setText(_translate("Dialog", "消力池池深", None))
        self.label_9.setText(_translate("Dialog", "<html><head/><body><p><img src=\":/images/xlczj.png\"/></p></body></html>", None))
        self.pushButton_7.setText(_translate("Dialog", "计算", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Q*ΔH最大设计情况", None))
        self.Label_45.setText(_translate("Dialog", "上游水深", None))
        self.Label_46.setText(_translate("Dialog", "下游水深", None))
        self.Label_47.setText(_translate("Dialog", "上下游水位差", None))
        self.Label_48.setText(_translate("Dialog", "单宽流量", None))
        self.Label_49.setText(_translate("Dialog", "消力池底板顶面算起的总势能", None))
        self.Label_50.setText(_translate("Dialog", "收缩水深", None))
        self.Label_51.setText(_translate("Dialog", "跃前断面水流弗劳德数", None))
        self.Label_52.setText(_translate("Dialog", "跃后水深", None))
        self.Label_53.setText(_translate("Dialog", "水跃淹没系数", None))
        self.Label_54.setText(_translate("Dialog", "过闸流量", None))
        self.Label_55.setText(_translate("Dialog", "消力池首宽", None))
        self.Label_56.setText(_translate("Dialog", "消力池末宽", None))
        self.Label_57.setText(_translate("Dialog", "上游水位", None))
        self.Label_58.setText(_translate("Dialog", "底板高程", None))
        self.Label_59.setText(_translate("Dialog", "下游水位", None))
        self.Label_60.setText(_translate("Dialog", "下游底高程", None))
        self.Label_61.setText(_translate("Dialog", "上游行进流速", None))
        self.Label_62.setText(_translate("Dialog", "重力加速度", None))
        self.Label_63.setText(_translate("Dialog", "流速系数", None))
        self.Label_64.setText(_translate("Dialog", "水流动能校正系数", None))
        self.Label_65.setText(_translate("Dialog", "闸孔总净宽", None))
        self.Label_66.setText(_translate("Dialog", "消力池池深", None))
        self.label_11.setText(_translate("Dialog", "<html><head/><body><p><img src=\":/images/xlczj.png\"/></p></body></html>", None))
        self.pushButton_9.setText(_translate("Dialog", "计算", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "水力要素计算", None))
        self.Label_67.setText(_translate("Dialog", "消力池底与闸底板高差 Δd", None))
        self.Label_68.setText(_translate("Dialog", "水跃长度校正系数 β", None))
        self.Label_69.setText(_translate("Dialog", "斜坡坡度系数 m", None))
        self.Label_70.setText(_translate("Dialog", "收缩水深 hc", None))
        self.Label_71.setText(_translate("Dialog", "跃后水深 hc\"", None))
        self.Label_72.setText(_translate("Dialog", "消力池水平投影长度Ls=m*d", None))
        self.Label_73.setText(_translate("Dialog", "自由水跃长度Lj=6.9(hc\"-hc)", None))
        self.Label_74.setText(_translate("Dialog", "消力池长度 Lsj=Ls+βLj", None))
        self.label_12.setText(_translate("Dialog", "输入参数", None))
        self.label_13.setText(_translate("Dialog", "计算过程", None))
        self.pushButton_10.setText(_translate("Dialog", "计算", None))
        self.label_14.setText(_translate("Dialog", "<html><head/><body><p><img src=\":/images/xlccc.png\"/></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Dialog", "消力池池长计算", None))

import xlcjs_rc
